# Generated by Django 5.2.17 on 2026-08-08 18:15

import apps.core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0003_stock_ledger'),
        ('masters', '0002_masters'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(editable=False, help_text='Allocated by apps.core.services.get_next_code, e.g. SI-2026-000123.', max_length=32, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=16)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True, default='')),
                ('amendment_no', models.PositiveIntegerField(default=0, help_text='0 for an original document, 1 for its first amendment, and so on.')),
                ('posting_date', models.DateField(db_index=True, help_text='The day this hits the books. Not the day it was typed in.')),
                ('vendor_bill_no', models.CharField(blank=True, db_index=True, default='', help_text="The supplier's own document number, as printed on their bill.", max_length=64)),
                ('vendor_bill_date', models.DateField(blank=True, help_text="The date on the supplier's bill, which is often not our posting date.", null=True)),
                ('subtotal_paisa', apps.core.fields.MoneyField(default=0, help_text='Sum of the line amounts, before discount and tax. Exact, never rounded.', non_negative=True)),
                ('discount_paisa', apps.core.fields.MoneyField(default=0, help_text='Sum of the line discounts. Posted to Discount Received.', non_negative=True)),
                ('tax_paisa', apps.core.fields.MoneyField(default=0, help_text='Sum of the line tax. Input tax — it reduces what is owed to the government.', non_negative=True)),
                ('total_paisa', apps.core.fields.MoneyField(default=0, help_text='subtotal - discount + tax. What the supplier is owed, or credits back.', non_negative=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('amended_from', models.ForeignKey(blank=True, help_text='The cancelled document this one replaces.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_amendments', to='purchasing.purchaseinvoice')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_cancelled', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_posted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(help_text='PROTECT: a vendor with documents cannot be deleted out from under them.', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='masters.vendor')),
                ('warehouse', models.ForeignKey(help_text='Where the goods land, or leave from. Valuation is per (item, warehouse).', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='accounting.warehouse')),
            ],
            options={
                'verbose_name': 'purchase invoice',
                'verbose_name_plural': 'purchase invoices',
                'ordering': ['-posting_date', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_input', apps.core.fields.QuantityField(default=0, help_text='Quantity exactly as typed, in unit_input. Kept so the line can be re-shown.')),
                ('unit_input', models.CharField(choices=[('PIECE', 'Piece'), ('CARTON', 'Carton')], default='PIECE', help_text='The unit qty_input is counted in. PIECE or CARTON.', max_length=8)),
                ('qty_base', apps.core.fields.QuantityField(default=0, help_text='qty_input converted to whole base units. Computed on save via masters.to_base.')),
                ('rate_paisa', apps.core.fields.MoneyField(default=0, help_text='Cost of ONE BASE UNIT, in paisa. Derived from amount_paisa and rounded once — the amount is the figure that was agreed, not this.', non_negative=True)),
                ('discount_paisa', apps.core.fields.MoneyField(default=0, help_text='Discount on this line, in paisa. Posted to Discount Received.', non_negative=True)),
                ('tax_paisa', apps.core.fields.MoneyField(default=0, help_text='Sales tax on this line, in paisa. Input tax on a purchase.', non_negative=True)),
                ('amount_paisa', apps.core.fields.MoneyField(default=0, help_text='qty_input x the rate that was typed, in paisa. Exact and never rounded. This is what the supplier billed and what inventory is debited.', non_negative=True)),
                ('document', models.ForeignKey(help_text='CASCADE: a line has no meaning without its invoice, and a DRAFT may be deleted.', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchasing.purchaseinvoice')),
                ('item', models.ForeignKey(help_text='PROTECT: an item on a posted document cannot be deleted.', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='masters.item')),
            ],
            options={
                'verbose_name': 'purchase invoice line',
                'verbose_name_plural': 'purchase invoice lines',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(editable=False, help_text='Allocated by apps.core.services.get_next_code, e.g. SI-2026-000123.', max_length=32, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=16)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True, default='')),
                ('amendment_no', models.PositiveIntegerField(default=0, help_text='0 for an original document, 1 for its first amendment, and so on.')),
                ('posting_date', models.DateField(db_index=True, help_text='The day this hits the books. Not the day it was typed in.')),
                ('vendor_bill_no', models.CharField(blank=True, db_index=True, default='', help_text="The supplier's own document number, as printed on their bill.", max_length=64)),
                ('vendor_bill_date', models.DateField(blank=True, help_text="The date on the supplier's bill, which is often not our posting date.", null=True)),
                ('subtotal_paisa', apps.core.fields.MoneyField(default=0, help_text='Sum of the line amounts, before discount and tax. Exact, never rounded.', non_negative=True)),
                ('discount_paisa', apps.core.fields.MoneyField(default=0, help_text='Sum of the line discounts. Posted to Discount Received.', non_negative=True)),
                ('tax_paisa', apps.core.fields.MoneyField(default=0, help_text='Sum of the line tax. Input tax — it reduces what is owed to the government.', non_negative=True)),
                ('total_paisa', apps.core.fields.MoneyField(default=0, help_text='subtotal - discount + tax. What the supplier is owed, or credits back.', non_negative=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('amended_from', models.ForeignKey(blank=True, help_text='The cancelled document this one replaces.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_amendments', to='purchasing.purchasereturn')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_cancelled', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_posted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(help_text='PROTECT: a vendor with documents cannot be deleted out from under them.', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='masters.vendor')),
                ('warehouse', models.ForeignKey(help_text='Where the goods land, or leave from. Valuation is per (item, warehouse).', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='accounting.warehouse')),
            ],
            options={
                'verbose_name': 'purchase return',
                'verbose_name_plural': 'purchase returns',
                'ordering': ['-posting_date', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturnLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_input', apps.core.fields.QuantityField(default=0, help_text='Quantity exactly as typed, in unit_input. Kept so the line can be re-shown.')),
                ('unit_input', models.CharField(choices=[('PIECE', 'Piece'), ('CARTON', 'Carton')], default='PIECE', help_text='The unit qty_input is counted in. PIECE or CARTON.', max_length=8)),
                ('qty_base', apps.core.fields.QuantityField(default=0, help_text='qty_input converted to whole base units. Computed on save via masters.to_base.')),
                ('rate_paisa', apps.core.fields.MoneyField(default=0, help_text='Cost of ONE BASE UNIT, in paisa. Derived from amount_paisa and rounded once — the amount is the figure that was agreed, not this.', non_negative=True)),
                ('discount_paisa', apps.core.fields.MoneyField(default=0, help_text='Discount on this line, in paisa. Posted to Discount Received.', non_negative=True)),
                ('tax_paisa', apps.core.fields.MoneyField(default=0, help_text='Sales tax on this line, in paisa. Input tax on a purchase.', non_negative=True)),
                ('amount_paisa', apps.core.fields.MoneyField(default=0, help_text='qty_input x the rate that was typed, in paisa. Exact and never rounded. This is what the supplier billed and what inventory is debited.', non_negative=True)),
                ('document', models.ForeignKey(help_text='CASCADE: a line has no meaning without its return, and a DRAFT may be deleted.', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchasing.purchasereturn')),
                ('item', models.ForeignKey(help_text='PROTECT: an item on a posted document cannot be deleted.', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='masters.item')),
            ],
            options={
                'verbose_name': 'purchase return line',
                'verbose_name_plural': 'purchase return lines',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='purchaseinvoice',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('vendor_bill_no', ''), _negated=True), models.Q(('status', 'CANCELLED'), _negated=True)), fields=('vendor', 'vendor_bill_no'), name='purchaseinvoice_unique_vendor_bill_no', violation_error_message='That bill number has already been entered for this supplier.'),
        ),
        migrations.AddConstraint(
            model_name='purchaseinvoiceline',
            constraint=models.CheckConstraint(condition=models.Q(('qty_input__gt', 0)), name='purchasing_purchaseinvoiceline_qty_input_positive', violation_error_message='A line moves a positive quantity.'),
        ),
        migrations.AddConstraint(
            model_name='purchaseinvoiceline',
            constraint=models.CheckConstraint(condition=models.Q(('qty_base__gt', 0)), name='purchasing_purchaseinvoiceline_qty_base_positive', violation_error_message='A line moves a positive number of base units.'),
        ),
        migrations.AddConstraint(
            model_name='purchaseinvoiceline',
            constraint=models.CheckConstraint(condition=models.Q(('discount_paisa__lte', models.F('amount_paisa'))), name='purchasing_purchaseinvoiceline_discount_within_amount', violation_error_message='A line discount cannot exceed the line amount.'),
        ),
        migrations.AddConstraint(
            model_name='purchasereturn',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('vendor_bill_no', ''), _negated=True), models.Q(('status', 'CANCELLED'), _negated=True)), fields=('vendor', 'vendor_bill_no'), name='purchasereturn_unique_vendor_bill_no', violation_error_message='That credit note number has already been entered for this supplier.'),
        ),
        migrations.AddConstraint(
            model_name='purchasereturnline',
            constraint=models.CheckConstraint(condition=models.Q(('qty_input__gt', 0)), name='purchasing_purchasereturnline_qty_input_positive', violation_error_message='A line moves a positive quantity.'),
        ),
        migrations.AddConstraint(
            model_name='purchasereturnline',
            constraint=models.CheckConstraint(condition=models.Q(('qty_base__gt', 0)), name='purchasing_purchasereturnline_qty_base_positive', violation_error_message='A line moves a positive number of base units.'),
        ),
        migrations.AddConstraint(
            model_name='purchasereturnline',
            constraint=models.CheckConstraint(condition=models.Q(('discount_paisa__lte', models.F('amount_paisa'))), name='purchasing_purchasereturnline_discount_within_amount', violation_error_message='A line discount cannot exceed the line amount.'),
        ),
    ]
