# Generated by Django 5.2.17 on 2026-08-08 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseinvoice',
            options={'ordering': ['-posting_date', '-id'], 'permissions': [('cancel_purchaseinvoice', 'Can cancel a purchase invoice and reverse its entries')], 'verbose_name': 'purchase invoice', 'verbose_name_plural': 'purchase invoices'},
        ),
        migrations.AlterModelOptions(
            name='purchasereturn',
            options={'ordering': ['-posting_date', '-id'], 'permissions': [('cancel_purchasereturn', 'Can cancel a purchase return and reverse its entries')], 'verbose_name': 'purchase return', 'verbose_name_plural': 'purchase returns'},
        ),
    ]
