# Generated by Django 5.2.17 on 2026-08-08 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0002_alter_purchaseinvoice_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseinvoice',
            options={'ordering': ['-posting_date', '-id'], 'permissions': [('post_purchaseinvoice', 'Can post a purchase invoice to the ledger'), ('cancel_purchaseinvoice', 'Can cancel a purchase invoice and reverse its entries'), ('amend_purchaseinvoice', 'Can raise an amendment of a cancelled purchase invoice')], 'verbose_name': 'purchase invoice', 'verbose_name_plural': 'purchase invoices'},
        ),
        migrations.AlterModelOptions(
            name='purchasereturn',
            options={'ordering': ['-posting_date', '-id'], 'permissions': [('post_purchasereturn', 'Can post a purchase return to the ledger'), ('cancel_purchasereturn', 'Can cancel a purchase return and reverse its entries'), ('amend_purchasereturn', 'Can raise an amendment of a cancelled purchase return')], 'verbose_name': 'purchase return', 'verbose_name_plural': 'purchase returns'},
        ),
    ]
