# Generated by Django 5.2.17 on 2026-08-08 18:49

import apps.core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0003_stock_ledger'),
        ('masters', '0002_masters'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(editable=False, help_text='Allocated by apps.core.services.get_next_code, e.g. SI-2026-000123.', max_length=32, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=16)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True, default='')),
                ('amendment_no', models.PositiveIntegerField(default=0, help_text='0 for an original document, 1 for its first amendment, and so on.')),
                ('posting_date', models.DateField(db_index=True, help_text='The day this hits the books. Not the day it was typed in.')),
                ('subtotal_paisa', apps.core.fields.MoneyField(default=0, help_text='Sum of the line amounts, before discount and tax. Exact, never rounded.', non_negative=True)),
                ('discount_paisa', apps.core.fields.MoneyField(default=0, help_text='Sum of the line discounts. Posted to Discount Allowed.', non_negative=True)),
                ('tax_paisa', apps.core.fields.MoneyField(default=0, help_text='Sum of the line tax. Output tax — it increases what is owed to the government.', non_negative=True)),
                ('total_paisa', apps.core.fields.MoneyField(default=0, help_text='subtotal - discount + tax. What the client owes, or is credited back.', non_negative=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('due_date', models.DateField(blank=True, db_index=True, help_text="When payment falls due. Defaults to posting_date + the client's credit days.", null=True)),
                ('amended_from', models.ForeignKey(blank=True, help_text='The cancelled document this one replaces.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_amendments', to='sales.salesinvoice')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_cancelled', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(help_text='PROTECT: a client with documents cannot be deleted out from under them.', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='masters.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_posted', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(blank=True, help_text="Defaults to the client's route. Override when the beat was covered.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='masters.route')),
                ('seller', models.ForeignKey(blank=True, help_text="Defaults to the client's usual booker. Override when someone covered.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='masters.seller')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(help_text='Where the goods leave from, or come back to. Valuation is per (item, warehouse).', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='accounting.warehouse')),
            ],
            options={
                'verbose_name': 'sales invoice',
                'verbose_name_plural': 'sales invoices',
                'ordering': ['-posting_date', '-id'],
                'permissions': [('override_credit_limit', 'Can post a sales invoice that takes a client over their credit limit')],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(editable=False, help_text='Allocated by apps.core.services.get_next_code, e.g. SI-2026-000123.', max_length=32, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=16)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True, default='')),
                ('amendment_no', models.PositiveIntegerField(default=0, help_text='0 for an original document, 1 for its first amendment, and so on.')),
                ('posting_date', models.DateField(db_index=True, help_text='The day this hits the books. Not the day it was typed in.')),
                ('subtotal_paisa', apps.core.fields.MoneyField(default=0, help_text='Sum of the line amounts, before discount and tax. Exact, never rounded.', non_negative=True)),
                ('discount_paisa', apps.core.fields.MoneyField(default=0, help_text='Sum of the line discounts. Posted to Discount Allowed.', non_negative=True)),
                ('tax_paisa', apps.core.fields.MoneyField(default=0, help_text='Sum of the line tax. Output tax — it increases what is owed to the government.', non_negative=True)),
                ('total_paisa', apps.core.fields.MoneyField(default=0, help_text='subtotal - discount + tax. What the client owes, or is credited back.', non_negative=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('against_invoice', models.ForeignKey(blank=True, help_text='The invoice these goods went out on, if it is known. Sets what they come back into stock at, and lets the quantities be checked.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='sales.salesinvoice')),
                ('amended_from', models.ForeignKey(blank=True, help_text='The cancelled document this one replaces.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_amendments', to='sales.salesreturn')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_cancelled', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(help_text='PROTECT: a client with documents cannot be deleted out from under them.', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='masters.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_posted', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(blank=True, help_text="Defaults to the client's route. Override when the beat was covered.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='masters.route')),
                ('seller', models.ForeignKey(blank=True, help_text="Defaults to the client's usual booker. Override when someone covered.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='masters.seller')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(help_text='Where the goods leave from, or come back to. Valuation is per (item, warehouse).', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='accounting.warehouse')),
            ],
            options={
                'verbose_name': 'sales return',
                'verbose_name_plural': 'sales returns',
                'ordering': ['-posting_date', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_input', apps.core.fields.QuantityField(default=0, help_text='Quantity exactly as typed, in unit_input. Kept so the line can be re-shown.')),
                ('unit_input', models.CharField(choices=[('PIECE', 'Piece'), ('CARTON', 'Carton')], default='PIECE', help_text='The unit qty_input is counted in. PIECE or CARTON.', max_length=8)),
                ('qty_base', apps.core.fields.QuantityField(default=0, help_text='qty_input converted to whole base units. Computed on save via masters.to_base.')),
                ('rate_paisa', apps.core.fields.MoneyField(default=0, help_text='Selling price of ONE BASE UNIT, in paisa. Derived from amount_paisa and rounded once — the amount is the figure that was agreed, not this.', non_negative=True)),
                ('discount_paisa', apps.core.fields.MoneyField(default=0, help_text='Discount on this line, in paisa. Posted to Discount Allowed.', non_negative=True)),
                ('tax_paisa', apps.core.fields.MoneyField(default=0, help_text='Sales tax on this line, in paisa. Output tax on a sale.', non_negative=True)),
                ('amount_paisa', apps.core.fields.MoneyField(default=0, help_text='qty_input x the rate that was typed, in paisa. Exact and never rounded. This is what the client was billed.', non_negative=True)),
                ('cogs_paisa', apps.core.fields.MoneyField(default=0, help_text='What these goods cost us, in paisa. CAPTURED AT POST TIME from the stock valuation and frozen there. Zero on a draft — before posting there is no answer.', non_negative=True)),
                ('document', models.ForeignKey(help_text='CASCADE: a line has no meaning without its invoice, and a DRAFT may be deleted.', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.salesinvoice')),
                ('item', models.ForeignKey(help_text='PROTECT: an item on a posted document cannot be deleted.', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='masters.item')),
            ],
            options={
                'verbose_name': 'sales invoice line',
                'verbose_name_plural': 'sales invoice lines',
                'ordering': ['id'],
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('qty_input__gt', 0)), name='sales_salesinvoiceline_qty_input_positive', violation_error_message='A line moves a positive quantity.'), models.CheckConstraint(condition=models.Q(('qty_base__gt', 0)), name='sales_salesinvoiceline_qty_base_positive', violation_error_message='A line moves a positive number of base units.'), models.CheckConstraint(condition=models.Q(('discount_paisa__lte', models.F('amount_paisa'))), name='sales_salesinvoiceline_discount_within_amount', violation_error_message='A line discount cannot exceed the line amount.')],
            },
        ),
        migrations.CreateModel(
            name='SalesReturnLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_input', apps.core.fields.QuantityField(default=0, help_text='Quantity exactly as typed, in unit_input. Kept so the line can be re-shown.')),
                ('unit_input', models.CharField(choices=[('PIECE', 'Piece'), ('CARTON', 'Carton')], default='PIECE', help_text='The unit qty_input is counted in. PIECE or CARTON.', max_length=8)),
                ('qty_base', apps.core.fields.QuantityField(default=0, help_text='qty_input converted to whole base units. Computed on save via masters.to_base.')),
                ('rate_paisa', apps.core.fields.MoneyField(default=0, help_text='Selling price of ONE BASE UNIT, in paisa. Derived from amount_paisa and rounded once — the amount is the figure that was agreed, not this.', non_negative=True)),
                ('discount_paisa', apps.core.fields.MoneyField(default=0, help_text='Discount on this line, in paisa. Posted to Discount Allowed.', non_negative=True)),
                ('tax_paisa', apps.core.fields.MoneyField(default=0, help_text='Sales tax on this line, in paisa. Output tax on a sale.', non_negative=True)),
                ('amount_paisa', apps.core.fields.MoneyField(default=0, help_text='qty_input x the rate that was typed, in paisa. Exact and never rounded. This is what the client was billed.', non_negative=True)),
                ('cogs_paisa', apps.core.fields.MoneyField(default=0, help_text='What these goods cost us, in paisa. CAPTURED AT POST TIME from the stock valuation and frozen there. Zero on a draft — before posting there is no answer.', non_negative=True)),
                ('document', models.ForeignKey(help_text='CASCADE: a line has no meaning without its return, and a DRAFT may be deleted.', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.salesreturn')),
                ('item', models.ForeignKey(help_text='PROTECT: an item on a posted document cannot be deleted.', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='masters.item')),
            ],
            options={
                'verbose_name': 'sales return line',
                'verbose_name_plural': 'sales return lines',
                'ordering': ['id'],
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('qty_input__gt', 0)), name='sales_salesreturnline_qty_input_positive', violation_error_message='A line moves a positive quantity.'), models.CheckConstraint(condition=models.Q(('qty_base__gt', 0)), name='sales_salesreturnline_qty_base_positive', violation_error_message='A line moves a positive number of base units.'), models.CheckConstraint(condition=models.Q(('discount_paisa__lte', models.F('amount_paisa'))), name='sales_salesreturnline_discount_within_amount', violation_error_message='A line discount cannot exceed the line amount.')],
            },
        ),
    ]
