# Generated by Django 5.2.17 on 2026-08-08 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesinvoice',
            options={'ordering': ['-posting_date', '-id'], 'permissions': [('override_credit_limit', 'Can post a sales invoice that takes a client over their credit limit'), ('cancel_salesinvoice', 'Can cancel a sales invoice and reverse its entries')], 'verbose_name': 'sales invoice', 'verbose_name_plural': 'sales invoices'},
        ),
        migrations.AlterModelOptions(
            name='salesreturn',
            options={'ordering': ['-posting_date', '-id'], 'permissions': [('cancel_salesreturn', 'Can cancel a credit note and reverse its entries')], 'verbose_name': 'sales return', 'verbose_name_plural': 'sales returns'},
        ),
    ]
