# Generated by Django 5.2.17 on 2026-08-08 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_salesinvoice_options_alter_salesreturn_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesinvoice',
            options={'ordering': ['-posting_date', '-id'], 'permissions': [('override_credit_limit', 'Can post a sales invoice that takes a client over their credit limit'), ('post_salesinvoice', 'Can post a sales invoice to the ledger'), ('cancel_salesinvoice', 'Can cancel a sales invoice and reverse its entries'), ('amend_salesinvoice', 'Can raise an amendment of a cancelled sales invoice')], 'verbose_name': 'sales invoice', 'verbose_name_plural': 'sales invoices'},
        ),
        migrations.AlterModelOptions(
            name='salesreturn',
            options={'ordering': ['-posting_date', '-id'], 'permissions': [('post_salesreturn', 'Can post a credit note to the ledger'), ('cancel_salesreturn', 'Can cancel a credit note and reverse its entries'), ('amend_salesreturn', 'Can raise an amendment of a cancelled credit note')], 'verbose_name': 'sales return', 'verbose_name_plural': 'sales returns'},
        ),
    ]
