# Generated by Django 5.2.17 on 2026-08-08 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0004_alter_item_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('must_change_password', models.BooleanField(default=True, help_text='Set when an administrator creates or resets this login. Until it is cleared, every page redirects to the password change screen.')),
                ('password_hash_at_grant', models.CharField(blank=True, default='', editable=False, help_text="The hash of the password the administrator set. Compared against the user's current one to notice that they have changed it.", max_length=128)),
                ('password_changed_at', models.DateTimeField(blank=True, help_text='When this user last set their own password. Never typed in.', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(blank=True, help_text="The booker this login belongs to. Their routes come from RouteSeller, and a user without 'view all routes' sees only those routes' shops.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='masters.seller')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user profile',
                'verbose_name_plural': 'user profiles',
                'permissions': [('view_all_routes', "Can see clients on every route, not only their own seller's"), ('manage_users', 'Can create users, assign groups and routes, and deactivate logins')],
            },
        ),
    ]
