# Generated by Django 5.2.17 on 2026-08-08 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_seed_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Set when an administrator creates or resets this login. Until it is cleared, every page redirects to the password change screen.'),
        ),
    ]
