# Generated by Django 5.2.17 on 2026-08-08 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='density',
            field=models.CharField(choices=[('comfortable', 'Comfortable'), ('compact', 'Compact')], default='comfortable', help_text='How tightly rows and controls are packed. Operators entering bills all day want compact; somebody reading a ledger usually does not.', max_length=12),
        ),
    ]
