# Generated by Django 5.2.17 on 2026-08-08 13:47

import apps.core.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Stable identifier, e.g. R-MON. Sorting by code gives report order.', max_length=16, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('day_of_week', models.CharField(blank=True, choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], db_index=True, help_text='The day this route is run. Empty for an unscheduled route.', max_length=3, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Deactivating keeps the route off new orders. Its clients are untouched.')),
            ],
            options={
                'verbose_name': 'route',
                'verbose_name_plural': 'routes',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='RouteSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_primary', models.BooleanField(default=False, help_text='The seller this route belongs to. At most one per route.')),
            ],
            options={
                'verbose_name': 'route seller',
                'verbose_name_plural': 'route sellers',
                'ordering': ['route__code', '-is_primary', 'seller__code'],
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Stable identifier, e.g. S-01. Appears on order books and commission reports.', max_length=16, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('is_active', models.BooleanField(default=True, help_text='Deactivating keeps the seller off new orders. It never hides history.')),
            ],
            options={
                'verbose_name': 'seller',
                'verbose_name_plural': 'sellers',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Stable identifier, e.g. C-0001. Appears on every document and statement.', max_length=16, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('address', models.TextField(blank=True, default='')),
                ('city', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('opening_balance_paisa', apps.core.fields.MoneyField(default=0, help_text='What was owed at go-live, in paisa. Positive means the normal direction of business (a client owes us, we owe a vendor). Data entry only — the live balance is aggregated from the ledger.')),
                ('credit_limit_paisa', apps.core.fields.MoneyField(default=0, help_text='Maximum outstanding allowed, in paisa. 0 means no credit is extended.', non_negative=True)),
                ('credit_days', models.PositiveIntegerField(default=0, help_text='Days before an invoice is overdue. 0 means cash on delivery.')),
                ('is_active', models.BooleanField(default=True, help_text='Deactivating keeps the party off new documents. It never hides history.')),
            ],
            options={
                'verbose_name': 'vendor',
                'verbose_name_plural': 'vendors',
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='item',
            name='base_unit',
            field=models.CharField(choices=[('PIECE', 'Piece'), ('CARTON', 'Carton')], default='PIECE', help_text='The unit one stored quantity of 1 means. Almost always PIECE. CARTON is for goods only ever moved as a sealed carton, and forces carton_size to 1.', max_length=8),
        ),
        migrations.AddField(
            model_name='item',
            name='carton_size',
            field=apps.core.fields.QuantityField(default=1, help_text='Base units in one carton. 1 means the item is not sold by the carton.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='item',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Deactivating keeps the item off new documents. It never hides history.'),
        ),
        migrations.AddField(
            model_name='item',
            name='purchase_rate_paisa',
            field=apps.core.fields.MoneyField(default=0, help_text='Default buying rate for ONE BASE UNIT, in paisa. A data-entry default only.', non_negative=True),
        ),
        migrations.AddField(
            model_name='item',
            name='sale_rate_paisa',
            field=apps.core.fields.MoneyField(default=0, help_text='Default selling rate for ONE BASE UNIT, in paisa. A data-entry default only.', non_negative=True),
        ),
        migrations.AddField(
            model_name='item',
            name='tax_rate_bp',
            field=models.PositiveIntegerField(default=0, help_text='Sales tax in basis points: 1750 is 17.5%, 0 is exempt.', validators=[django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Stable identifier, e.g. C-0001. Appears on every document and statement.', max_length=16, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('address', models.TextField(blank=True, default='')),
                ('city', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('opening_balance_paisa', apps.core.fields.MoneyField(default=0, help_text='What was owed at go-live, in paisa. Positive means the normal direction of business (a client owes us, we owe a vendor). Data entry only — the live balance is aggregated from the ledger.')),
                ('credit_limit_paisa', apps.core.fields.MoneyField(default=0, help_text='Maximum outstanding allowed, in paisa. 0 means no credit is extended.', non_negative=True)),
                ('credit_days', models.PositiveIntegerField(default=0, help_text='Days before an invoice is overdue. 0 means cash on delivery.')),
                ('is_active', models.BooleanField(default=True, help_text='Deactivating keeps the party off new documents. It never hides history.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, help_text='The category this one sits under. Empty for a top-level category.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='masters.itemcategory')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'item category',
                'verbose_name_plural': 'item categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Optional grouping for reports and for finding things in a long list.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='masters.itemcategory'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['name'], name='item_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(condition=models.Q(('carton_size__gte', 1)), name='item_carton_size_at_least_one', violation_error_message='A carton holds at least one base unit.'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(condition=models.Q(('tax_rate_bp__gte', 0), ('tax_rate_bp__lte', 10000)), name='item_tax_rate_within_range', violation_error_message='Tax rate is between 0 and 10000 basis points.'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('base_unit', 'CARTON'), _negated=True), ('carton_size', 1), _connector='OR'), name='item_carton_base_unit_holds_one', violation_error_message='An item counted in cartons has a carton_size of 1 — the carton is already the base unit.'),
        ),
        migrations.AddField(
            model_name='route',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='route',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='route',
            field=models.ForeignKey(blank=True, help_text='The beat this shop is delivered on. Empty for a walk-in.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='masters.route'),
        ),
        migrations.AddField(
            model_name='routeseller',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='routeseller',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_sellers', to='masters.route'),
        ),
        migrations.AddField(
            model_name='routeseller',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seller',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seller',
            name='routes',
            field=models.ManyToManyField(blank=True, help_text='The routes this seller works. One of them may be marked primary.', related_name='sellers', through='masters.RouteSeller', to='masters.route'),
        ),
        migrations.AddField(
            model_name='seller',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='routeseller',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_sellers', to='masters.seller'),
        ),
        migrations.AddField(
            model_name='client',
            name='seller',
            field=models.ForeignKey(blank=True, help_text='The order booker who usually serves this shop. A default, not a restriction.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='masters.seller'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendor',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='itemcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', False)), fields=('parent', 'name'), name='itemcategory_unique_name_per_parent', violation_error_message='That category already has a child with this name.'),
        ),
        migrations.AddConstraint(
            model_name='itemcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('name',), name='itemcategory_unique_root_name', violation_error_message='A top-level category with this name already exists.'),
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.CheckConstraint(condition=models.Q(('day_of_week', ''), _negated=True), name='route_day_is_null_not_blank', violation_error_message='An unscheduled route has no day at all, not a blank one.'),
        ),
        migrations.AddConstraint(
            model_name='routeseller',
            constraint=models.UniqueConstraint(fields=('route', 'seller'), name='routeseller_unique_pair', violation_error_message='That seller is already on this route.'),
        ),
        migrations.AddConstraint(
            model_name='routeseller',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('route',), name='routeseller_one_primary_per_route', violation_error_message='This route already has a primary seller.'),
        ),
    ]
