# Generated by Django 5.2.17 on 2026-08-08 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_historicalclient_historicalitem_historicalroute_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['code'], 'permissions': [('view_cost_price', 'Can see cost prices: COGS, margin, valuation rates and purchase rates')], 'verbose_name': 'item', 'verbose_name_plural': 'items'},
        ),
    ]
