# Generated by Django 5.2.17 on 2026-08-09 07:22

import apps.core.fields
import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_alter_item_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalitem',
            name='reorder_level_pieces',
            field=apps.core.fields.QuantityField(default=0, help_text='Reorder when the position falls to this many BASE UNITS. 0 means this item is not watched.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='item',
            name='reorder_level_pieces',
            field=apps.core.fields.QuantityField(default=0, help_text='Reorder when the position falls to this many BASE UNITS. 0 means this item is not watched.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(condition=models.Q(('reorder_level_pieces__gte', 0)), name='item_reorder_level_not_negative', violation_error_message='A reorder level is zero or more base units.'),
        ),
    ]
