# Generated by Django 5.2.17 on 2026-08-08 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'backup',
                'verbose_name_plural': 'backup',
                'permissions': [('run_backup', 'Can take a backup of the database'), ('restore_backup', 'Can restore the database from a backup, overwriting it')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
