# Generated by Django 5.2.17 on 2026-08-09 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run_id', models.CharField(db_index=True, help_text='The archive stamp, e.g. 20260809-2100. Shared by the rows of one run.', max_length=32)),
                ('destination', models.CharField(choices=[('LOCAL', 'Local disk'), ('USB', 'USB drive'), ('DRIVE', 'Google Drive')], max_length=8)),
                ('outcome', models.CharField(choices=[('OK', 'Succeeded'), ('WARNING', 'Completed with a warning'), ('FAILED', 'Failed')], max_length=8)),
                ('filename', models.CharField(blank=True, default='', help_text='Archive name, without a directory. The directory differs per destination.', max_length=255)),
                ('size_bytes', models.BigIntegerField(default=0, help_text='Size of the archive. Zero when the attempt never got as far as a file.')),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('target', models.CharField(blank=True, default='', help_text='Where it was written: a directory, or an rclone remote.', max_length=500)),
                ('message', models.TextField(blank=True, default='', help_text='Why it failed or warned, in words somebody can act on.')),
                ('duration_ms', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'backup log',
                'verbose_name_plural': 'backup log',
                'ordering': ['-created_at', 'destination'],
                'indexes': [models.Index(fields=['-created_at'], name='backuplog_recent_idx'), models.Index(fields=['outcome', '-created_at'], name='backuplog_outcome_idx')],
            },
        ),
    ]
