# Generated by Django 5.2.17 on 2026-08-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=8)),
                ('fiscal_year', models.PositiveIntegerField()),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'document sequence',
                'ordering': ['prefix', 'fiscal_year'],
                'constraints': [models.UniqueConstraint(fields=('prefix', 'fiscal_year'), name='core_documentsequence_unique_prefix_year')],
            },
        ),
    ]
