# Generated by Django 5.2.17 on 2026-08-08 12:45

import apps.core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Stable identifier, e.g. 1110. Sorting by code gives chart order.', max_length=16, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity'), ('INCOME', 'Income'), ('EXPENSE', 'Expense')], db_index=True, help_text='Decides whether a debit raises or lowers this account. Not a label.', max_length=16)),
                ('is_group', models.BooleanField(default=False, help_text='A group is a heading: it is totalled from its children and never posted to.')),
                ('is_active', models.BooleanField(default=True, help_text='Deactivating blocks new postings. It never hides or alters history.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, help_text='The group this account sits under. Empty for a root.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounting.account')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'account',
                'verbose_name_plural': 'chart of accounts',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('posting_date', models.DateField(db_index=True, help_text='The day this hits the books. Not the day the row was written.')),
                ('debit_paisa', apps.core.fields.MoneyField(default=0, non_negative=True)),
                ('credit_paisa', apps.core.fields.MoneyField(default=0, non_negative=True)),
                ('party_type', models.CharField(blank=True, choices=[('CLIENT', 'Client'), ('VENDOR', 'Vendor')], help_text='NULL on rows that are not a receivable or payable.', max_length=8, null=True)),
                ('party_id', models.BigIntegerField(blank=True, help_text='Soft link to masters. Deliberately not a foreign key.', null=True)),
                ('voucher_type', models.CharField(help_text='The document model name, e.g. "SalesInvoice".', max_length=64)),
                ('voucher_id', models.BigIntegerField()),
                ('voucher_code', models.CharField(help_text='Denormalised document code, so reports never join to find it.', max_length=32)),
                ('is_reversal', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, default='')),
                ('account', models.ForeignKey(help_text='PROTECT: an account with history cannot be deleted out from under it.', on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='accounting.account')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reverses', models.ForeignKey(blank=True, help_text='The row this one cancels out. Set on reversals, NULL otherwise.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by', to='accounting.ledgerentry')),
            ],
            options={
                'verbose_name': 'ledger entry',
                'verbose_name_plural': 'ledger entries',
                'ordering': ['posting_date', 'id'],
                'indexes': [models.Index(fields=['account', 'posting_date'], name='ledger_account_date_idx'), models.Index(fields=['party_type', 'party_id'], name='ledger_party_idx'), models.Index(fields=['voucher_type', 'voucher_id'], name='ledger_voucher_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('debit_paisa__gte', 0), ('credit_paisa__gte', 0)), name='ledgerentry_amounts_non_negative', violation_error_message='Ledger amounts are never negative; swap the side instead.'), models.CheckConstraint(condition=models.Q(models.Q(('credit_paisa', 0), ('debit_paisa__gt', 0)), models.Q(('credit_paisa__gt', 0), ('debit_paisa', 0)), _connector='OR'), name='ledgerentry_exactly_one_side', violation_error_message='A ledger entry is exactly one non-zero debit or credit.'), models.CheckConstraint(condition=models.Q(models.Q(('party_id__isnull', True), ('party_type__isnull', True)), models.Q(('party_id__isnull', False), ('party_type__isnull', False)), _connector='OR'), name='ledgerentry_party_is_a_pair', violation_error_message='party_type and party_id are set together or not at all.'), models.CheckConstraint(condition=models.Q(models.Q(('is_reversal', True), ('reverses__isnull', False)), models.Q(('is_reversal', False), ('reverses__isnull', True)), _connector='OR'), name='ledgerentry_reversal_points_at_something', violation_error_message='A reversal names the row it reverses; nothing else does.'), models.UniqueConstraint(condition=models.Q(('reverses__isnull', False)), fields=('reverses',), name='ledgerentry_one_reversal_per_row', violation_error_message='That entry has already been reversed.')],
            },
        ),
    ]
