# Generated by Django 5.2.17 on 2026-08-08 13:15

import apps.core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_seed_chart_of_accounts'),
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Stable identifier, e.g. MAIN. Sorting by code gives report order.', max_length=16, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('is_default', models.BooleanField(default=False, help_text='The warehouse a document uses when it does not name one. At most one.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'warehouse',
                'verbose_name_plural': 'warehouses',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='StockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('posting_date', models.DateField(db_index=True, help_text='The day this hits the stock card. Not the day the row was written.')),
                ('qty_base', apps.core.fields.QuantityField(default=0, help_text='Signed base units: positive in, negative out. Never fractional.')),
                ('rate_paisa', apps.core.fields.MoneyField(default=0, help_text='Cost of one base unit at the moment this row was written.', non_negative=True)),
                ('value_paisa', apps.core.fields.MoneyField(default=0, help_text='Signed cost value moved. The figure balances are summed from.')),
                ('voucher_type', models.CharField(help_text='The document model name, e.g. "SalesInvoice".', max_length=64)),
                ('voucher_id', models.BigIntegerField()),
                ('voucher_code', models.CharField(help_text='Denormalised document code, so reports never join to find it.', max_length=32)),
                ('is_reversal', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(help_text='PROTECT: an item with movement cannot be deleted out from under it.', on_delete=django.db.models.deletion.PROTECT, related_name='stock_entries', to='masters.item')),
                ('reverses', models.ForeignKey(blank=True, help_text='The row this one cancels out. Set on reversals, NULL otherwise.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by', to='accounting.stockentry')),
                ('warehouse', models.ForeignKey(help_text='PROTECT: a warehouse with movement cannot be deleted out from under it.', on_delete=django.db.models.deletion.PROTECT, related_name='stock_entries', to='accounting.warehouse')),
            ],
            options={
                'verbose_name': 'stock entry',
                'verbose_name_plural': 'stock entries',
                'ordering': ['posting_date', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='warehouse_one_default', violation_error_message='Another warehouse is already the default.'),
        ),
        migrations.AddIndex(
            model_name='stockentry',
            index=models.Index(fields=['item', 'warehouse', 'posting_date'], name='stock_item_wh_date_idx'),
        ),
        migrations.AddIndex(
            model_name='stockentry',
            index=models.Index(fields=['item', 'posting_date'], name='stock_item_date_idx'),
        ),
        migrations.AddIndex(
            model_name='stockentry',
            index=models.Index(fields=['voucher_type', 'voucher_id'], name='stock_voucher_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockentry',
            constraint=models.CheckConstraint(condition=models.Q(('qty_base', 0), _negated=True), name='stockentry_qty_is_not_zero', violation_error_message='A stock entry moves a non-zero quantity.'),
        ),
        migrations.AddConstraint(
            model_name='stockentry',
            constraint=models.CheckConstraint(condition=models.Q(('rate_paisa__gte', 0)), name='stockentry_rate_non_negative', violation_error_message='A cost rate is never negative.'),
        ),
        migrations.AddConstraint(
            model_name='stockentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('qty_base__gt', 0), ('value_paisa__gte', 0)), models.Q(('qty_base__lt', 0), ('value_paisa__lte', 0)), _connector='OR'), name='stockentry_value_follows_qty', violation_error_message='Quantity and value must move in the same direction.'),
        ),
        migrations.AddConstraint(
            model_name='stockentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_reversal', True), ('reverses__isnull', False)), models.Q(('is_reversal', False), ('reverses__isnull', True)), _connector='OR'), name='stockentry_reversal_points_at_something', violation_error_message='A reversal names the row it reverses; nothing else does.'),
        ),
        migrations.AddConstraint(
            model_name='stockentry',
            constraint=models.UniqueConstraint(condition=models.Q(('reverses__isnull', False)), fields=('reverses',), name='stockentry_one_reversal_per_row', violation_error_message='That entry has already been reversed.'),
        ),
    ]
