# Generated by Django 5.2.17 on 2026-08-08 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_historicalaccount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockentry',
            options={'ordering': ['posting_date', 'id'], 'permissions': [('override_negative_stock', 'Can issue stock a warehouse does not hold, taking it below zero')], 'verbose_name': 'stock entry', 'verbose_name_plural': 'stock entries'},
        ),
    ]
