# Generated by Django 5.2.17 on 2026-08-09 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_alter_stockentry_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrityRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ok', models.BooleanField(db_index=True)),
                ('checks_run', models.PositiveSmallIntegerField(default=0)),
                ('checks_failed', models.PositiveSmallIntegerField(default=0)),
                ('duration_ms', models.IntegerField(default=0)),
                ('report', models.TextField(blank=True, default='', help_text='The full text of what the run printed, so the dashboard can link to it.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'integrity run',
                'verbose_name_plural': 'integrity runs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='integrityrun_recent_idx')],
            },
        ),
    ]
