# Generated by Django 5.2.17 on 2026-08-09 12:20

import apps.core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_integrityrun'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalYearClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(editable=False, help_text='Allocated by apps.core.services.get_next_code, e.g. SI-2026-000123.', max_length=32, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=16)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True, default='')),
                ('amendment_no', models.PositiveIntegerField(default=0, help_text='0 for an original document, 1 for its first amendment, and so on.')),
                ('fiscal_year', models.PositiveIntegerField(help_text='The year being closed. Unique: a year is closed once.', unique=True)),
                ('posting_date', models.DateField(help_text='The last day of the year being closed. Every entry lands on it.')),
                ('profit_paisa', apps.core.fields.MoneyField(default=0, help_text='The figure carried to Retained Earnings. A display convenience only (CLAUDE.md §6) - every report re-aggregates the ledger.')),
                ('amended_from', models.ForeignKey(blank=True, help_text='The cancelled document this one replaces.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_amendments', to='accounting.fiscalyearclose')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_cancelled', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_posted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'fiscal year close',
                'verbose_name_plural': 'fiscal year closes',
                'ordering': ['-fiscal_year'],
                'permissions': [('post_fiscalyearclose', 'Can close a fiscal year'), ('cancel_fiscalyearclose', 'Can reverse a fiscal year close'), ('amend_fiscalyearclose', 'Can amend a cancelled fiscal year close')],
            },
        ),
    ]
