# Generated by Django 5.2.17 on 2026-08-09 12:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_fiscalyearclose'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalyearclose',
            name='fiscal_year',
            field=models.PositiveIntegerField(db_index=True, help_text='The year being closed.'),
        ),
        migrations.AddConstraint(
            model_name='fiscalyearclose',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'CANCELLED'), _negated=True), fields=('fiscal_year',), name='one_live_close_per_fiscal_year'),
        ),
    ]
