# Generated by Django 5.2.17 on 2026-08-09 12:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_alter_fiscalyearclose_fiscal_year_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['party_type', 'party_id', 'voucher_type', 'voucher_id', 'voucher_code', 'posting_date', 'debit_paisa', 'credit_paisa'], name='ledger_party_voucher_idx'),
        ),
    ]
