# Generated by Django 5.2.17 on 2026-08-08 19:26

import apps.core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0002_masters'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(editable=False, help_text='Allocated by apps.core.services.get_next_code, e.g. SI-2026-000123.', max_length=32, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=16)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True, default='')),
                ('amendment_no', models.PositiveIntegerField(default=0, help_text='0 for an original document, 1 for its first amendment, and so on.')),
                ('party_type', models.CharField(choices=[('CLIENT', 'Client'), ('VENDOR', 'Vendor')], db_index=True, help_text='CLIENT or VENDOR. The party account follows from this, not from direction.', max_length=8)),
                ('party_id', models.BigIntegerField(help_text='Soft link to masters, exactly as the ledger carries it.')),
                ('direction', models.CharField(choices=[('RECEIVE', 'Received'), ('PAY', 'Paid')], db_index=True, help_text='Which way the money went. Independent of the party type.', max_length=8)),
                ('mode', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank'), ('CHEQUE', 'Cheque')], db_index=True, help_text='Cash, bank transfer, or cheque. Decides which account the money lands in.', max_length=8)),
                ('posting_date', models.DateField(db_index=True, help_text='The day the money changed hands. Not the day it was typed in.')),
                ('amount_paisa', apps.core.fields.MoneyField(default=0, help_text='What moved, in paisa. Always positive — direction carries the sign.', non_negative=True)),
                ('cheque_no', models.CharField(blank=True, db_index=True, default='', help_text='The number on the cheque. Required when mode is CHEQUE, empty otherwise.', max_length=32)),
                ('cheque_date', models.DateField(blank=True, db_index=True, help_text='The date written on the cheque, which for a post-dated cheque is the earliest it can be banked. Not the day it was taken.', null=True)),
                ('bank_name', models.CharField(blank=True, default='', help_text='The bank the cheque is drawn on. Optional even on a cheque.', max_length=128)),
                ('remarks', models.TextField(blank=True, default='')),
                ('amended_from', models.ForeignKey(blank=True, help_text='The cancelled document this one replaces.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_amendments', to='payments.payment')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_cancelled', to=settings.AUTH_USER_MODEL)),
                ('collected_by', models.ForeignKey(blank=True, help_text='Who physically collected it. PROTECT: a seller with collections stays.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments_collected', to='masters.seller')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_posted', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(blank=True, help_text='The beat this collection belongs to. Recovery is reported per route.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='masters.route')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
                'ordering': ['-posting_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ChequeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(editable=False, help_text='Allocated by apps.core.services.get_next_code, e.g. SI-2026-000123.', max_length=32, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=16)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True, default='')),
                ('amendment_no', models.PositiveIntegerField(default=0, help_text='0 for an original document, 1 for its first amendment, and so on.')),
                ('kind', models.CharField(choices=[('CLEARED', 'Cleared'), ('BOUNCED', 'Bounced')], db_index=True, help_text='What the bank did. Both are postings, not flags.', max_length=8)),
                ('posting_date', models.DateField(db_index=True, help_text='The day the bank did it. Not the day the cheque was taken.')),
                ('remarks', models.TextField(blank=True, default='')),
                ('amended_from', models.ForeignKey(blank=True, help_text='The cancelled document this one replaces.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_amendments', to='payments.chequeevent')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_cancelled', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_posted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(help_text='PROTECT: a payment whose cheque has been settled cannot be deleted.', on_delete=django.db.models.deletion.PROTECT, related_name='cheque_events', to='payments.payment')),
            ],
            options={
                'verbose_name': 'cheque event',
                'verbose_name_plural': 'cheque events',
                'ordering': ['-posting_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_type', models.CharField(help_text='The document model name, e.g. "SalesInvoice". See ALLOCATABLE_DOCUMENTS.', max_length=64)),
                ('invoice_id', models.BigIntegerField(help_text='Soft link to the document. Deliberately not a foreign key.')),
                ('amount_paisa', apps.core.fields.MoneyField(default=0, help_text='How much of the payment lands on this document, in paisa.', non_negative=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(help_text='CASCADE: an allocation has no meaning without its payment.', on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='payments.payment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'payment allocation',
                'verbose_name_plural': 'payment allocations',
                'ordering': ['payment_id', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['party_type', 'party_id'], name='payment_party_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['posting_date', 'route'], name='payment_date_route_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['mode', 'cheque_date'], name='payment_cheque_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paisa__gt', 0)), name='payment_amount_is_positive', violation_error_message='A payment moves a positive amount.'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cheque_date__isnull', False), ('mode', 'CHEQUE'), models.Q(('cheque_no', ''), _negated=True)), models.Q(models.Q(('mode', 'CHEQUE'), _negated=True), ('bank_name', ''), ('cheque_date__isnull', True), ('cheque_no', '')), _connector='OR'), name='payment_cheque_fields_match_mode', violation_error_message='A cheque carries a number and a date; nothing else carries either.'),
        ),
        migrations.AddConstraint(
            model_name='chequeevent',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'POSTED')), fields=('payment',), name='chequeevent_one_settlement_per_payment', violation_error_message='That cheque has already been settled.'),
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['invoice_type', 'invoice_id'], name='allocation_document_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentallocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paisa__gt', 0)), name='paymentallocation_amount_is_positive', violation_error_message='An allocation applies a positive amount.'),
        ),
        migrations.AddConstraint(
            model_name='paymentallocation',
            constraint=models.UniqueConstraint(fields=('payment', 'invoice_type', 'invoice_id'), name='paymentallocation_one_row_per_document', violation_error_message='That payment is already allocated to this document.'),
        ),
    ]
