# Generated by Django 5.2.17 on 2026-08-08 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chequeevent',
            options={'ordering': ['-posting_date', '-id'], 'permissions': [('cancel_chequeevent', 'Can cancel a cheque clearing or bounce and reverse its entries')], 'verbose_name': 'cheque event', 'verbose_name_plural': 'cheque events'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-posting_date', '-id'], 'permissions': [('cancel_payment', 'Can cancel a receipt or payment and reverse its entries')], 'verbose_name': 'payment', 'verbose_name_plural': 'payments'},
        ),
    ]
