# Generated by Django 5.2.17 on 2026-08-08 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_chequeevent_options_alter_payment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chequeevent',
            options={'ordering': ['-posting_date', '-id'], 'permissions': [('post_chequeevent', 'Can record that the bank cleared or bounced a cheque'), ('cancel_chequeevent', 'Can cancel a cheque clearing or bounce and reverse its entries'), ('amend_chequeevent', 'Can raise an amendment of a cancelled cheque event')], 'verbose_name': 'cheque event', 'verbose_name_plural': 'cheque events'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-posting_date', '-id'], 'permissions': [('post_payment', 'Can post a receipt or payment to the ledger'), ('cancel_payment', 'Can cancel a receipt or payment and reverse its entries'), ('amend_payment', 'Can raise an amendment of a cancelled receipt or payment')], 'verbose_name': 'payment', 'verbose_name_plural': 'payments'},
        ),
    ]
