# Generated by Django 5.2.17 on 2026-08-08 21:00

import apps.reports.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', help_text='The trading name, as it should appear on a bill.', max_length=200)),
                ('address', models.TextField(blank=True, default='', help_text='Street address, printed under the name. Line breaks are kept.')),
                ('phone', models.CharField(blank=True, default='', help_text='One or two numbers, comma separated. Printed in the header.', max_length=64)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('ntn', models.CharField(blank=True, default='', help_text='National Tax Number. Printed on every invoice; leave blank if unregistered.', max_length=32, verbose_name='NTN')),
                ('strn', models.CharField(blank=True, default='', help_text='Sales Tax Registration Number, when the business is sales-tax registered.', max_length=32, verbose_name='STRN')),
                ('logo', models.FileField(blank=True, help_text='JPEG or PNG, stored on this machine. Roughly 600x200 prints well. Never a link to an image on the internet — this PC has none.', null=True, upload_to='company/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png']), apps.reports.models.logo_path_is_local])),
                ('footer_text', models.TextField(blank=True, default='', help_text='Printed at the foot of every page, above the page number. Terms, a thank-you, a bank account — whatever the business puts on its bills.')),
                ('invoice_terms', models.TextField(blank=True, default='', help_text='Longer terms printed once at the end of an invoice, under the totals.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'company profile',
                'verbose_name_plural': 'company profile',
            },
        ),
    ]
