# Generated by Django 5.2.17 on 2026-08-08 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'report access',
                'verbose_name_plural': 'report access',
                'permissions': [('view_reports', 'Can open the reports section'), ('view_reports_financial', 'Can open the financial statements: Profit & Loss, Balance Sheet, Trial Balance')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
